-- ISO 21502 supplementary management fields (Epic 15 / Story 15.1)

CREATE TABLE project_iso_management (
    project_id UUID PRIMARY KEY REFERENCES projects (id) ON DELETE CASCADE,
    expected_benefit VARCHAR(500) NOT NULL,
    benefit_unit VARCHAR(80) NOT NULL,
    realized_percent INTEGER NOT NULL,
    benefits_status VARCHAR(10) NOT NULL,
    scope_status VARCHAR(120) NOT NULL,
    deviation_1 VARCHAR(300),
    deviation_2 VARCHAR(300),
    scope_trend VARCHAR(20) NOT NULL,
    cr_total INTEGER NOT NULL,
    cr_open INTEGER NOT NULL,
    cr_in_review INTEGER NOT NULL,
    cr_approved INTEGER NOT NULL,
    impact_schedule VARCHAR(10) NOT NULL,
    impact_cost VARCHAR(10) NOT NULL,
    impact_scope VARCHAR(10) NOT NULL,
    quality_status VARCHAR(120) NOT NULL,
    open_defects INTEGER NOT NULL,
    critical_defects INTEGER NOT NULL,
    test_acceptance_status VARCHAR(200) NOT NULL,
    quality_progress_percent INTEGER NOT NULL,
    sponsor_customer VARCHAR(200) NOT NULL,
    stakeholder_status VARCHAR(120) NOT NULL,
    escalation_status VARCHAR(120) NOT NULL,
    last_steering_date DATE,
    facts_as_of TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT chk_iso_benefits_status CHECK (benefits_status IN ('GREEN', 'AMBER', 'RED')),
    CONSTRAINT chk_iso_scope_trend CHECK (scope_trend IN ('IMPROVING', 'STABLE', 'DETERIORATING')),
    CONSTRAINT chk_iso_impact_schedule CHECK (impact_schedule IN ('NONE', 'LOW', 'MEDIUM', 'HIGH')),
    CONSTRAINT chk_iso_impact_cost CHECK (impact_cost IN ('NONE', 'LOW', 'MEDIUM', 'HIGH')),
    CONSTRAINT chk_iso_impact_scope CHECK (impact_scope IN ('NONE', 'LOW', 'MEDIUM', 'HIGH'))
);
